2016-04-24 09:56:59,230 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2016-04-24 09:56:59,240 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2016-04-24 09:57:04,832 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10797ded8>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1079657d0>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10798e6d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x107977450>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': '\\xe9\\xb8\\x9f\\xe5\\x98\\x8c\\xe5\\x91\\xa4\\xe7\\x9a\\x84\\xe4\\xb8\\xaa\\xe4\\xba\\xba\\xe5\\x8d\\x9a\\xe5\\xae\\xa2'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 09:57:04,834 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10797ded8>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1079657d0>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10798e6d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x107977450>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': '\\xe9\\xb8\\x9f\\xe5\\x98\\x8c\\xe5\\x91\\xa4\\xe7\\x9a\\x84\\xe4\\xb8\\xaa\\xe4\\xba\\xba\\xe5\\x8d\\x9a\\xe5\\xae\\xa2'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 09:57:04,834 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10797ded8>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1079657d0>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10798e6d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x107977450>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': '\\xe9\\xb8\\x9f\\xe5\\x98\\x8c\\xe5\\x91\\xa4\\xe7\\x9a\\x84\\xe4\\xb8\\xaa\\xe4\\xba\\xba\\xe5\\x8d\\x9a\\xe5\\xae\\xa2'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 10:00:00,270 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2016-04-24 10:00:00,273 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2016-04-24 10:00:08,348 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x105f48ed8>>, 'user': <SimpleLazyObject: <function <lambda> at 0x105f317d0>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x105f54d90>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x105f3bb10>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': '\\xe9\\xb8\\x9f\\xe5\\x98\\x8c\\xe5\\x91\\xa4\\xe7\\x9a\\x84\\xe4\\xb8\\xaa\\xe4\\xba\\xba\\xe5\\x8d\\x9a\\xe5\\xae\\xa2'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 10:00:08,349 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x105f48ed8>>, 'user': <SimpleLazyObject: <function <lambda> at 0x105f317d0>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x105f54d90>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x105f3bb10>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': '\\xe9\\xb8\\x9f\\xe5\\x98\\x8c\\xe5\\x91\\xa4\\xe7\\x9a\\x84\\xe4\\xb8\\xaa\\xe4\\xba\\xba\\xe5\\x8d\\x9a\\xe5\\xae\\xa2'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 10:00:08,350 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x105f48ed8>>, 'user': <SimpleLazyObject: <function <lambda> at 0x105f317d0>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x105f54d90>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x105f3bb10>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': '\\xe9\\xb8\\x9f\\xe5\\x98\\x8c\\xe5\\x91\\xa4\\xe7\\x9a\\x84\\xe4\\xb8\\xaa\\xe4\\xba\\xba\\xe5\\x8d\\x9a\\xe5\\xae\\xa2'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 10:01:19,415 [Thread-48:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x105f6dd70>>, 'user': <SimpleLazyObject: <function <lambda> at 0x105f6dcf8>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x105f999d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x105fc2810>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': '\\xe9\\xb8\\x9f\\xe5\\x98\\x8c\\xe5\\x91\\xa4\\xe7\\x9a\\x84\\xe4\\xb8\\xaa\\xe4\\xba\\xba\\xe5\\x8d\\x9a\\xe5\\xae\\xa2'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 10:02:45,028 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2016-04-24 10:02:45,031 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2016-04-24 10:02:49,861 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x109480ed8>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10946a7d0>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x109491a10>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x109473b10>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 10:03:34,520 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2016-04-24 10:03:34,525 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2016-04-24 10:03:50,170 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2016-04-24 10:03:50,173 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2016-04-24 10:04:33,634 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2016-04-24 10:04:33,637 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2016-04-24 10:04:35,866 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {'SITE_NAME ': 'http://weibo.sina.com/yopoing', 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81'}]"
2016-04-24 10:05:14,970 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2016-04-24 10:05:14,973 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2016-04-24 10:05:17,898 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x1110cded8>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1110b77d0>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x1110dea10>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1110c0b10>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 10:55:04,718 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 10:57:59,142 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 10:57:59,254 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 10:57:59,269 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.015) SHOW FULL TABLES; args=None
2016-04-24 10:57:59,269 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime NOT NULL); (params None)
2016-04-24 10:57:59,420 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.151) CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime NOT NULL); args=None
2016-04-24 10:57:59,496 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.075) SELECT engine FROM information_schema.tables WHERE table_name = 'django_migrations'; args=[u'django_migrations']
2016-04-24 10:57:59,529 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.013) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 10:57:59,534 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `django_content_type` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL); (params None)
2016-04-24 10:57:59,682 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.147) CREATE TABLE `django_content_type` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL); args=None
2016-04-24 10:57:59,683 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'django_content_type'; args=[u'django_content_type']
2016-04-24 10:57:59,686 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_content_type` ADD CONSTRAINT `django_content_type_app_label_76bd3d3b_uniq` UNIQUE (`app_label`, `model`); (params [])
2016-04-24 10:58:00,213 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.527) ALTER TABLE `django_content_type` ADD CONSTRAINT `django_content_type_app_label_76bd3d3b_uniq` UNIQUE (`app_label`, `model`); args=[]
2016-04-24 10:58:00,214 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:00,243 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.027) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('contenttypes', '0001_initial', '2016-04-24 10:58:00'); args=['contenttypes', u'0001_initial', u'2016-04-24 10:58:00']
2016-04-24 10:58:00,249 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_permission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `content_type_id` integer NOT NULL, `codename` varchar(100) NOT NULL); (params None)
2016-04-24 10:58:00,452 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.202) CREATE TABLE `auth_permission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `content_type_id` integer NOT NULL, `codename` varchar(100) NOT NULL); args=None
2016-04-24 10:58:00,453 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_permission'; args=[u'auth_permission']
2016-04-24 10:58:00,461 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE); (params None)
2016-04-24 10:58:00,553 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.091) CREATE TABLE `auth_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE); args=None
2016-04-24 10:58:00,554 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_group'; args=[u'auth_group']
2016-04-24 10:58:00,555 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_group_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_id` integer NOT NULL, `permission_id` integer NOT NULL); (params None)
2016-04-24 10:58:00,653 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.098) CREATE TABLE `auth_group_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_id` integer NOT NULL, `permission_id` integer NOT NULL); args=None
2016-04-24 10:58:00,654 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_group_permissions'; args=[u'auth_group_permissions']
2016-04-24 10:58:00,668 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime NOT NULL, `is_superuser` bool NOT NULL, `username` varchar(30) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(30) NOT NULL, `email` varchar(75) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime NOT NULL); (params None)
2016-04-24 10:58:00,779 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.110) CREATE TABLE `auth_user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime NOT NULL, `is_superuser` bool NOT NULL, `username` varchar(30) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(30) NOT NULL, `email` varchar(75) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime NOT NULL); args=None
2016-04-24 10:58:00,780 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_user'; args=[u'auth_user']
2016-04-24 10:58:00,781 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_user_groups` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `group_id` integer NOT NULL); (params None)
2016-04-24 10:58:00,878 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.097) CREATE TABLE `auth_user_groups` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `group_id` integer NOT NULL); args=None
2016-04-24 10:58:00,879 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_user_groups'; args=[u'auth_user_groups']
2016-04-24 10:58:00,881 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `auth_user_user_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `permission_id` integer NOT NULL); (params None)
2016-04-24 10:58:01,001 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.120) CREATE TABLE `auth_user_user_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `permission_id` integer NOT NULL); args=None
2016-04-24 10:58:01,003 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_user_user_permissions'; args=[u'auth_user_user_permissions']
2016-04-24 10:58:01,003 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permissi_content_type_id_2f476e4b_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params [])
2016-04-24 10:58:01,150 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.147) ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permissi_content_type_id_2f476e4b_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); args=[]
2016-04-24 10:58:01,150 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permission_content_type_id_01ab375a_uniq` UNIQUE (`content_type_id`, `codename`); (params [])
2016-04-24 10:58:01,239 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.088) ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permission_content_type_id_01ab375a_uniq` UNIQUE (`content_type_id`, `codename`); args=[]
2016-04-24 10:58:01,239 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
2016-04-24 10:58:01,357 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.117) ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); args=[]
2016-04-24 10:58:01,357 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissi_permission_id_84c5c92e_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
2016-04-24 10:58:01,482 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.124) ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissi_permission_id_84c5c92e_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); args=[]
2016-04-24 10:58:01,482 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_0cd325b0_uniq` UNIQUE (`group_id`, `permission_id`); (params [])
2016-04-24 10:58:01,596 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.114) ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_0cd325b0_uniq` UNIQUE (`group_id`, `permission_id`); args=[]
2016-04-24 10:58:01,597 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
2016-04-24 10:58:01,695 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.098) ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); args=[]
2016-04-24 10:58:01,695 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
2016-04-24 10:58:01,818 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.122) ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); args=[]
2016-04-24 10:58:01,818 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_94350c0c_uniq` UNIQUE (`user_id`, `group_id`); (params [])
2016-04-24 10:58:01,955 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.137) ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_94350c0c_uniq` UNIQUE (`user_id`, `group_id`); args=[]
2016-04-24 10:58:01,955 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
2016-04-24 10:58:02,070 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.114) ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); args=[]
2016-04-24 10:58:02,070 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_perm_permission_id_1fbb5f2c_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
2016-04-24 10:58:02,196 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.125) ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_perm_permission_id_1fbb5f2c_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); args=[]
2016-04-24 10:58:02,196 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissions_user_id_14a6b632_uniq` UNIQUE (`user_id`, `permission_id`); (params [])
2016-04-24 10:58:02,322 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.126) ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissions_user_id_14a6b632_uniq` UNIQUE (`user_id`, `permission_id`); args=[]
2016-04-24 10:58:02,323 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:02,325 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0001_initial', '2016-04-24 10:58:02'); args=['auth', u'0001_initial', u'2016-04-24 10:58:02']
2016-04-24 10:58:02,345 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `django_admin_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `action_time` datetime NOT NULL, `object_id` longtext NULL, `object_repr` varchar(200) NOT NULL, `action_flag` smallint UNSIGNED NOT NULL, `change_message` longtext NOT NULL, `content_type_id` integer NULL, `user_id` integer NOT NULL); (params None)
2016-04-24 10:58:02,456 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.111) CREATE TABLE `django_admin_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `action_time` datetime NOT NULL, `object_id` longtext NULL, `object_repr` varchar(200) NOT NULL, `action_flag` smallint UNSIGNED NOT NULL, `change_message` longtext NOT NULL, `content_type_id` integer NULL, `user_id` integer NOT NULL); args=None
2016-04-24 10:58:02,457 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'django_admin_log'; args=[u'django_admin_log']
2016-04-24 10:58:02,458 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin__content_type_id_c4bce8eb_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params [])
2016-04-24 10:58:02,595 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.137) ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin__content_type_id_c4bce8eb_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); args=[]
2016-04-24 10:58:02,596 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
2016-04-24 10:58:02,732 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.136) ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); args=[]
2016-04-24 10:58:02,734 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:02,736 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('admin', '0001_initial', '2016-04-24 10:58:02'); args=['admin', u'0001_initial', u'2016-04-24 10:58:02']
2016-04-24 10:58:02,753 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_admin_log` ALTER COLUMN `action_time` SET DEFAULT %s; (params [u'2016-04-24 10:58:02'])
2016-04-24 10:58:02,869 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.116) ALTER TABLE `django_admin_log` ALTER COLUMN `action_time` SET DEFAULT '2016-04-24 10:58:02'; args=[u'2016-04-24 10:58:02']
2016-04-24 10:58:02,870 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_admin_log` ALTER COLUMN `action_time` DROP DEFAULT; (params [])
2016-04-24 10:58:02,959 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.089) ALTER TABLE `django_admin_log` ALTER COLUMN `action_time` DROP DEFAULT; args=[]
2016-04-24 10:58:02,961 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:02,962 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('admin', '0002_logentry_remove_auto_add', '2016-04-24 10:58:02'); args=['admin', u'0002_logentry_remove_auto_add', u'2016-04-24 10:58:02']
2016-04-24 10:58:02,994 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_content_type` MODIFY `name` varchar(100) NULL; (params [])
2016-04-24 10:58:03,122 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.127) ALTER TABLE `django_content_type` MODIFY `name` varchar(100) NULL; args=[]
2016-04-24 10:58:03,140 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `django_content_type` DROP COLUMN `name` CASCADE; (params [])
2016-04-24 10:58:03,268 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.127) ALTER TABLE `django_content_type` DROP COLUMN `name` CASCADE; args=[]
2016-04-24 10:58:03,269 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:03,271 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('contenttypes', '0002_remove_content_type_name', '2016-04-24 10:58:03'); args=['contenttypes', u'0002_remove_content_type_name', u'2016-04-24 10:58:03']
2016-04-24 10:58:03,289 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_permission` MODIFY `name` varchar(255) NOT NULL; (params [])
2016-04-24 10:58:03,416 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.127) ALTER TABLE `auth_permission` MODIFY `name` varchar(255) NOT NULL; args=[]
2016-04-24 10:58:03,418 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:03,420 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0002_alter_permission_name_max_length', '2016-04-24 10:58:03'); args=['auth', u'0002_alter_permission_name_max_length', u'2016-04-24 10:58:03']
2016-04-24 10:58:03,436 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user` MODIFY `email` varchar(254) NOT NULL; (params [])
2016-04-24 10:58:03,561 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.124) ALTER TABLE `auth_user` MODIFY `email` varchar(254) NOT NULL; args=[]
2016-04-24 10:58:03,563 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:03,565 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0003_alter_user_email_max_length', '2016-04-24 10:58:03'); args=['auth', u'0003_alter_user_email_max_length', u'2016-04-24 10:58:03']
2016-04-24 10:58:03,583 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:03,585 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0004_alter_user_username_opts', '2016-04-24 10:58:03'); args=['auth', u'0004_alter_user_username_opts', u'2016-04-24 10:58:03']
2016-04-24 10:58:03,606 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- ALTER TABLE `auth_user` MODIFY `last_login` datetime NULL; (params [])
2016-04-24 10:58:03,694 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.088) ALTER TABLE `auth_user` MODIFY `last_login` datetime NULL; args=[]
2016-04-24 10:58:03,696 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:03,697 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0005_alter_user_last_login_null', '2016-04-24 10:58:03'); args=['auth', u'0005_alter_user_last_login_null', u'2016-04-24 10:58:03']
2016-04-24 10:58:03,700 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:03,701 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0006_require_contenttypes_0002', '2016-04-24 10:58:03'); args=['auth', u'0006_require_contenttypes_0002', u'2016-04-24 10:58:03']
2016-04-24 10:58:03,718 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:03,720 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0007_alter_validators_add_error_messages', '2016-04-24 10:58:03'); args=['auth', u'0007_alter_validators_add_error_messages', u'2016-04-24 10:58:03']
2016-04-24 10:58:03,725 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` longtext NOT NULL, `expire_date` datetime NOT NULL); (params None)
2016-04-24 10:58:03,825 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.099) CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` longtext NOT NULL, `expire_date` datetime NOT NULL); args=None
2016-04-24 10:58:03,826 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'django_session'; args=[u'django_session']
2016-04-24 10:58:03,827 [MainThread:140735144259584] [django.db.backends.schema:101] [schema:execute] [DEBUG]- CREATE INDEX `django_session_de54fa62` ON `django_session` (`expire_date`); (params [])
2016-04-24 10:58:03,959 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.132) CREATE INDEX `django_session_de54fa62` ON `django_session` (`expire_date`); args=[]
2016-04-24 10:58:03,961 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:03,962 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('sessions', '0001_initial', '2016-04-24 10:58:03'); args=['sessions', u'0001_initial', u'2016-04-24 10:58:03']
2016-04-24 10:58:03,964 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 10:58:03,966 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 10:58:03,969 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'logentry' AND `django_content_type`.`app_label` = 'admin'); args=('logentry', 'admin')
2016-04-24 10:58:03,971 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'logentry' AND `django_content_type`.`app_label` = 'admin'); args=('logentry', 'admin')
2016-04-24 10:58:03,972 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('admin', 'logentry'); args=['admin', 'logentry']
2016-04-24 10:58:04,356 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.380) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (1) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(1,)
2016-04-24 10:58:04,358 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add log entry', 1, 'add_logentry'), ('Can change log entry', 1, 'change_logentry'), ('Can delete log entry', 1, 'delete_logentry'); args=(u'Can add log entry', 1, u'add_logentry', u'Can change log entry', 1, u'change_logentry', u'Can delete log entry', 1, u'delete_logentry')
2016-04-24 10:58:04,360 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'admin'; args=('admin',)
2016-04-24 10:58:04,362 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'permission' AND `django_content_type`.`app_label` = 'auth'); args=('permission', 'auth')
2016-04-24 10:58:04,364 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'permission' AND `django_content_type`.`app_label` = 'auth'); args=('permission', 'auth')
2016-04-24 10:58:04,365 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('auth', 'permission'); args=['auth', 'permission']
2016-04-24 10:58:04,368 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'group' AND `django_content_type`.`app_label` = 'auth'); args=('group', 'auth')
2016-04-24 10:58:04,370 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'group' AND `django_content_type`.`app_label` = 'auth'); args=('group', 'auth')
2016-04-24 10:58:04,371 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('auth', 'group'); args=['auth', 'group']
2016-04-24 10:58:04,374 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'user' AND `django_content_type`.`app_label` = 'auth'); args=('user', 'auth')
2016-04-24 10:58:04,376 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'user' AND `django_content_type`.`app_label` = 'auth'); args=('user', 'auth')
2016-04-24 10:58:04,377 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('auth', 'user'); args=['auth', 'user']
2016-04-24 10:58:04,616 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.228) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (2, 3, 4) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(2, 3, 4)
2016-04-24 10:58:04,618 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add permission', 2, 'add_permission'), ('Can change permission', 2, 'change_permission'), ('Can delete permission', 2, 'delete_permission'), ('Can add group', 3, 'add_group'), ('Can change group', 3, 'change_group'), ('Can delete group', 3, 'delete_group'), ('Can add user', 4, 'add_user'), ('Can change user', 4, 'change_user'), ('Can delete user', 4, 'delete_user'); args=(u'Can add permission', 2, u'add_permission', u'Can change permission', 2, u'change_permission', u'Can delete permission', 2, u'delete_permission', u'Can add group', 3, u'add_group', u'Can change group', 3, u'change_group', u'Can delete group', 3, u'delete_group', u'Can add user', 4, u'add_user', u'Can change user', 4, u'change_user', u'Can delete user', 4, u'delete_user')
2016-04-24 10:58:04,621 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'auth'; args=('auth',)
2016-04-24 10:58:04,623 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'contenttype' AND `django_content_type`.`app_label` = 'contenttypes'); args=('contenttype', 'contenttypes')
2016-04-24 10:58:04,625 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'contenttype' AND `django_content_type`.`app_label` = 'contenttypes'); args=('contenttype', 'contenttypes')
2016-04-24 10:58:04,626 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('contenttypes', 'contenttype'); args=['contenttypes', 'contenttype']
2016-04-24 10:58:04,629 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (5) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(5,)
2016-04-24 10:58:04,631 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add content type', 5, 'add_contenttype'), ('Can change content type', 5, 'change_contenttype'), ('Can delete content type', 5, 'delete_contenttype'); args=(u'Can add content type', 5, u'add_contenttype', u'Can change content type', 5, u'change_contenttype', u'Can delete content type', 5, u'delete_contenttype')
2016-04-24 10:58:04,641 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'contenttypes'; args=('contenttypes',)
2016-04-24 10:58:04,643 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'session' AND `django_content_type`.`app_label` = 'sessions'); args=('session', 'sessions')
2016-04-24 10:58:04,645 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'session' AND `django_content_type`.`app_label` = 'sessions'); args=('session', 'sessions')
2016-04-24 10:58:04,646 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('sessions', 'session'); args=['sessions', 'session']
2016-04-24 10:58:04,653 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (6) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(6,)
2016-04-24 10:58:04,655 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add session', 6, 'add_session'), ('Can change session', 6, 'change_session'), ('Can delete session', 6, 'delete_session'); args=(u'Can add session', 6, u'add_session', u'Can change session', 6, u'change_session', u'Can delete session', 6, u'delete_session')
2016-04-24 10:58:04,663 [MainThread:140735144259584] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'sessions'; args=('sessions',)
2016-04-24 12:49:13,245 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 12:49:30,593 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 12:49:30,865 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 12:49:30,968 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.102) SHOW FULL TABLES; args=None
2016-04-24 12:49:30,994 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 12:49:37,205 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x1099e2cf8>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1099c85f0>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x1099f23d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1099d9490>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 12:50:41,987 [Thread-8:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x109a06de8>>, 'user': <SimpleLazyObject: <function <lambda> at 0x109a06cf8>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x1099f23d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1099a5210>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:18:02,109 [Thread-9:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x109a06d70>>, 'user': <SimpleLazyObject: <function <lambda> at 0x109a06de8>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x109a1b090>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1099d9fd0>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:19:52,361 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:19:53,239 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:19:53,680 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.441) SHOW FULL TABLES; args=None
2016-04-24 13:19:53,719 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 13:20:14,664 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10f1e5758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10f1c1050>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10f1e38d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10f1c89d0>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:25:44,189 [Thread-23:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10f1fd758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10f1fd6e0>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10f21bb50>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10f201d10>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:25:44,190 [Thread-23:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10f1fd758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10f1fd6e0>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10f21bb50>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10f201d10>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:31:23,574 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:32:19,880 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:32:20,499 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:32:20,601 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.101) SHOW FULL TABLES; args=None
2016-04-24 13:32:20,628 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 13:32:29,707 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10e62c938>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10e609050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10e623fd0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10e5ffed0>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:32:29,709 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10e62c938>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10e609050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10e623fd0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10e5ffed0>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:35:21,936 [Thread-25:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10e63f6e0>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10e63f7d0>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10e65b550>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10e5c1750>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:35:21,937 [Thread-25:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10e63f6e0>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10e63f7d0>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10e65b550>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10e5c1750>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:38:02,551 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:38:02,838 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:38:02,943 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.104) SHOW FULL TABLES; args=None
2016-04-24 13:38:02,970 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 13:38:07,820 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10b48a848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10b466140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10b48d090>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10b45ef90>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:38:07,822 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10b48a848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10b466140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10b48d090>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10b45ef90>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:38:37,141 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:38:37,239 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:38:37,241 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2016-04-24 13:38:37,246 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 13:38:41,245 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10f996758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10f972050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10f98ef90>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10f969ed0>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:38:41,246 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10f996758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10f972050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10f98ef90>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10f969ed0>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:39:12,597 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:39:12,679 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:39:12,681 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 13:39:12,684 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 13:39:18,364 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10d71e758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10d6f9050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10d715fd0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10d6f1f10>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:39:18,366 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10d71e758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10d6f9050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10d715fd0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10d6f1f10>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:41:37,095 [Thread-12:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10d6f9050>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10d733758>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10d6f1fd0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10d731dd0>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:42:19,772 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:42:19,850 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:42:19,851 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 13:42:19,854 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 13:47:00,665 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:47:01,180 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:47:01,283 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.102) SHOW FULL TABLES; args=None
2016-04-24 13:47:01,311 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 13:47:12,791 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10f121758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10f0fe050>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10f119fd0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10f0f5f10>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:47:12,793 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEIBO_TENCENT' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEIBO_TENCENT] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10f121758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10f0fe050>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10f119fd0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10f0f5f10>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:48:57,796 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:48:57,881 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:48:57,882 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 13:48:57,885 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 13:49:21,125 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x101eff848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x101edb140>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x101f01090>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x101ed4f90>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:49:21,127 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEIBO_TENCENT' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEIBO_TENCENT] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x101eff848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x101edb140>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x101f01090>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x101ed4f90>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:49:42,197 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.002) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:49:42,290 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:49:42,291 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 13:49:42,294 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 13:49:47,120 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x103228758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x103203050>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10321ff90>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1031faed0>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:49:47,123 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEIBO_TENCENT' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEIBO_TENCENT] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x103228758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x103203050>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10321ff90>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1031faed0>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 13:50:32,696 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:50:32,779 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:50:32,780 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 13:50:32,783 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 13:51:10,148 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:51:10,242 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:51:10,244 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 13:51:10,246 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 13:51:23,907 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:51:29,654 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:51:47,694 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:51:47,801 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 13:51:47,803 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 13:51:47,806 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:06:45,720 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:06:46,222 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:06:46,328 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.105) SHOW FULL TABLES; args=None
2016-04-24 14:06:46,354 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:08:46,814 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:08:46,913 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:08:46,914 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:08:46,918 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:08:49,563 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10b763848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10b73e140>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10b766090>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10b736f90>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:08:49,565 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEIBO_TENCENT' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEIBO_TENCENT] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10b763848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10b73e140>>, 'SITE_DESC ': '\\xe4\\xb8\\x93\\xe6\\xb3\\xa8python\\xe5\\xbc\\x80\\xe5\\x8f\\x91,\\xe6\\xac\\xa2\\xe8\\xbf\\x8e\\xe5\\x92\\x8c\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe4\\xba\\xa4\\xe6\\xb5\\x81', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10b766090>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10b736f90>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:17:44,883 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:17:45,156 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:17:45,254 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.097) SHOW FULL TABLES; args=None
2016-04-24 14:17:45,281 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:17:47,540 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x1109ea848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1109c5140>>, 'SITE_DESC ': 'Welcome to comunication', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x1109e3ed0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1109c2e10>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:17:47,543 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEIBO_TENCENT' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEIBO_TENCENT] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x1109ea848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1109c5140>>, 'SITE_DESC ': 'Welcome to comunication', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x1109e3ed0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1109c2e10>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:18:30,444 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:18:30,530 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:18:30,532 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:18:30,534 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:18:33,337 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10a93d848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10a918140>>, 'SITE_DESC ': 'Welcome to comunication', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10a93f290>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10a910fd0>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:18:33,340 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10a93d848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10a918140>>, 'SITE_DESC ': 'Welcome to comunication', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10a93f290>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10a910fd0>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:18:33,341 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10a93d848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10a918140>>, 'SITE_DESC ': 'Welcome to comunication', 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10a93f290>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10a910fd0>, u'request': <WSGIRequest: GET '/'>, 'SITE_NAME ': 'http://weibo.sina.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:19:39,472 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:19:39,577 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:19:39,578 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:19:39,581 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:19:44,141 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:19:44,312 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:19:44,315 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:19:44,322 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:19:45,451 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITES_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITES_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x107220758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1071fd050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x107221210>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1071f3f50>, 'SITES_DESC ': 'Welcome to comunication', u'request': <WSGIRequest: GET '/'>, 'SITES_NAME ': 'This is My personal Blog'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:19:45,452 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITES_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITES_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x107220758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1071fd050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x107221210>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1071f3f50>, 'SITES_DESC ': 'Welcome to comunication', u'request': <WSGIRequest: GET '/'>, 'SITES_NAME ': 'This is My personal Blog'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:19:45,453 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITES_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITES_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x107220758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1071fd050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x107221210>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1071f3f50>, 'SITES_DESC ': 'Welcome to comunication', u'request': <WSGIRequest: GET '/'>, 'SITES_NAME ': 'This is My personal Blog'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:20:58,401 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:20:58,510 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:20:58,511 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:20:58,515 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:22:23,862 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITES_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITES_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x110088848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x110063140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x11008a290>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x11005bfd0>, 'SITES_DESC ': 'Welcome to comunication', u'request': <WSGIRequest: GET '/'>, 'SITES_NAME ': 'This is My personal Blog'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:22:23,895 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITES_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITES_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x110088848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x110063140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x11008a290>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x11005bfd0>, 'SITES_DESC ': 'Welcome to comunication', u'request': <WSGIRequest: GET '/'>, 'SITES_NAME ': 'This is My personal Blog'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:22:23,895 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITES_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [SITES_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x110088848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x110063140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x11008a290>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x11005bfd0>, 'SITES_DESC ': 'Welcome to comunication', u'request': <WSGIRequest: GET '/'>, 'SITES_NAME ': 'This is My personal Blog'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:22:53,053 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:22:53,150 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:22:53,151 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:22:53,154 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:25:41,833 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:25:41,930 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:25:41,931 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:25:41,934 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:25:54,774 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:25:54,861 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:25:54,863 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:25:54,866 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:26:07,735 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:26:07,823 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:26:07,824 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:26:07,827 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:26:44,046 [Thread-8:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10e788c08>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10e788b18>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10e789950>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10e77e610>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:26:44,052 [Thread-8:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10e788c08>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10e788b18>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10e789950>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10e77e610>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:26:44,053 [Thread-8:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10e788c08>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10e788b18>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10e789950>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10e77e610>, u'request': <WSGIRequest: GET '/'>, 'WEIBO_SINA': 'http://weibo.sina.com/yopoing', 'WEIBO_TENCENT': 'http://weibo.qq.com/yopoing'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:27:11,672 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:27:11,763 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:27:11,765 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:27:11,767 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:27:20,997 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:27:21,113 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:27:21,115 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:27:21,119 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:27:24,034 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'This is My personal Blog', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x103477758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x103453050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x103478210>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x103449f50>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'Welcome to comunication'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:27:24,035 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'This is My personal Blog', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x103477758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x103453050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x103478210>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x103449f50>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'Welcome to comunication'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:27:24,036 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'This is My personal Blog', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x103477758>>, 'user': <SimpleLazyObject: <function <lambda> at 0x103453050>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x103478210>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x103449f50>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'Welcome to comunication'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:27:39,988 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:27:40,080 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:27:40,082 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:27:40,085 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:27:43,414 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'GGGGGGGG', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10f416848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10f3f2140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10f4181d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10f3ecf10>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'HHFDH'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:27:43,417 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'GGGGGGGG', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10f416848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10f3f2140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10f4181d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10f3ecf10>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'HHFDH'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:27:43,418 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'GGGGGGGG', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10f416848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10f3f2140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10f4181d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10f3ecf10>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'HHFDH'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:28:09,314 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:28:09,400 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:28:09,401 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:28:09,404 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:28:46,612 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:28:46,694 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:28:46,696 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:28:46,698 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:29:15,727 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:29:15,819 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:29:15,820 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:29:15,824 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:29:37,764 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:29:37,853 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:29:37,854 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:29:37,858 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:29:39,633 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'This is My personal Blog', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10ce9e848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10ce78140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10ce9f250>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10ce70f90>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'Welcome to comunication'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:29:39,635 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'This is My personal Blog', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10ce9e848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10ce78140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10ce9f250>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10ce70f90>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'Welcome to comunication'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:29:39,636 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'This is My personal Blog', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x10ce9e848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x10ce78140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10ce9f250>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x10ce70f90>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'Welcome to comunication'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:30:30,305 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:30:30,399 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:30:30,401 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:30:30,404 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:31:12,643 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:31:12,738 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:31:12,740 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:31:12,743 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:31:13,899 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'This is My personal Blog', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x1027f4848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1027cf140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x1027f5290>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1027c7fd0>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'Welcome to comunication'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:31:13,901 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_NAME] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'This is My personal Blog', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x1027f4848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1027cf140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x1027f5290>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1027c7fd0>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'Welcome to comunication'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:31:13,901 [Thread-2:123145310715904] [django.template:927] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'WEBSITE_DESC' in template 'index.html'.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [WEBSITE_DESC] in u"[{'False': False, 'None': None, 'True': True}, {'WEBSITE_NAME ': 'This is My personal Blog', u'csrf_token': <SimpleLazyObject: <function _get_val at 0x1027f4848>>, 'user': <SimpleLazyObject: <function <lambda> at 0x1027cf140>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x1027f5290>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1027c7fd0>, u'request': <WSGIRequest: GET '/'>, 'WEBSITE_DESC ': 'Welcome to comunication'}, {}, {'request': <WSGIRequest: GET '/'>}]"
2016-04-24 14:31:43,810 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:31:43,907 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:31:43,908 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:31:43,911 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:32:22,083 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:32:22,178 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:32:22,179 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:32:22,182 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:32:49,143 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:32:49,237 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:32:49,238 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:32:49,242 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:33:18,124 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:33:18,218 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:33:18,219 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:33:18,223 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2016-04-24 14:33:41,223 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:33:41,304 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
2016-04-24 14:33:41,306 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2016-04-24 14:33:41,309 [Dummy-1:123145306509312] [django.db.backends:89] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
